#!/bin/bash
# run_openfoam.sh — OpenFOAM pipeline for heatsink optimisation
#
# Called by optimize_heatsink.py via:
#   multipass exec rewarded-bluefish -- bash '<path>/run_openfoam.sh' <work_dir> <results_dir>
#
# Arguments:
#   $1  WORK     = local work directory inside VM  (e.g. /tmp/heatsink-opt/run_001)
#   $2  RESULTS  = persistent results directory    (e.g. /mnt/results/runs/run_001)

source /usr/lib/openfoam/openfoam2506/etc/bashrc 2>/dev/null

WORK="$1"
RESULTS="$2"

if [ -z "$WORK" ] || [ -z "$RESULTS" ]; then
    echo "ERROR: Usage: $0 <work_dir> <results_dir>"
    exit 1
fi

echo "=== Preparing work directory ==="
rm -rf "$WORK"
mkdir -p "$WORK/constant/triSurface"

# Copy system/ and 0/ (patched by host Python)
cp -r "$RESULTS/system" "$WORK/"
cp -r "$RESULTS/0"      "$WORK/"

# Copy only the essential constant files (NOT polyMesh - regenerated by blockMesh)
for fname in g radiationProperties thermophysicalProperties turbulenceProperties; do
    [ -f "$RESULTS/constant/$fname" ] && cp "$RESULTS/constant/$fname" "$WORK/constant/"
done
cp "$RESULTS/constant/triSurface/heatsink.stl" "$WORK/constant/triSurface/"

echo "Case ready in $WORK"
cd "$WORK"

# blockMesh
echo "=== blockMesh ==="
blockMesh > log.blockMesh 2>&1
if [ $? -ne 0 ]; then
    echo "FAILED: blockMesh"; tail -15 log.blockMesh; exit 1
fi
echo "blockMesh OK"

# surfaceFeatureExtract
echo "=== surfaceFeatureExtract ==="
surfaceFeatureExtract > log.surfaceFeatureExtract 2>&1
if [ $? -ne 0 ]; then
    echo "FAILED: surfaceFeatureExtract"; tail -15 log.surfaceFeatureExtract; exit 1
fi
echo "surfaceFeatureExtract OK"

# snappyHexMesh -- serial (feature refinement disabled in snappyHexMeshDict)
echo "=== snappyHexMesh (serial) ==="
snappyHexMesh -overwrite > log.snappyHexMesh 2>&1
if [ $? -ne 0 ]; then
    echo "FAILED: snappyHexMesh"; tail -20 log.snappyHexMesh; exit 1
fi
echo "snappyHexMesh OK"
grep 'Cells per refinement level' -A10 log.snappyHexMesh 2>/dev/null | head -12

# buoyantSimpleFoam
echo "=== buoyantSimpleFoam ==="
buoyantSimpleFoam > log.buoyantSimpleFoam 2>&1
if [ $? -ne 0 ]; then
    echo "FAILED: buoyantSimpleFoam"; tail -20 log.buoyantSimpleFoam; exit 1
fi
echo "SOLVER_OK"
echo "=== Last residuals ==="
tail -12 log.buoyantSimpleFoam

# foamToVTK (non-fatal if it fails)
echo "=== foamToVTK ==="
foamToVTK -latestTime > log.foamToVTK 2>&1 && echo "foamToVTK OK" || echo "WARNING: foamToVTK failed (non-fatal)"

# Copy results back to Sid
echo "=== Copying results to $RESULTS ==="
cp log.* "$RESULTS/" 2>/dev/null

rm -rf "$RESULTS/constant/polyMesh"
cp -r  "$WORK/constant/polyMesh" "$RESULTS/constant/" 2>/dev/null

rm -rf "$RESULTS/constant/extendedFeatureEdgeMesh"
cp -r  "$WORK/constant/extendedFeatureEdgeMesh" "$RESULTS/constant/" 2>/dev/null

rm -rf "$RESULTS/postProcessing"
cp -r  "$WORK/postProcessing" "$RESULTS/" 2>/dev/null

rm -rf "$RESULTS/VTK"
cp -r  "$WORK/VTK" "$RESULTS/" 2>/dev/null

LAST=$(ls -d "$WORK"/[0-9]* 2>/dev/null | sort -V | tail -1)
if [ -n "$LAST" ]; then
    TNAME=$(basename "$LAST")
    if [ "$TNAME" != "0" ]; then
        rm -rf "$RESULTS/$TNAME"
        cp -r  "$LAST" "$RESULTS/"
        echo "Copied time directory: $TNAME"
    fi
fi

echo "=== wallHeatFlux integral ==="
find "$RESULTS/postProcessing" -name "wallHeatFlux.dat" 2>/dev/null | head -1 | xargs cat 2>/dev/null | tail -3

echo "=== Cleanup ==="
rm -rf "$WORK"
echo "Work directory removed"
echo "=== PIPELINE_COMPLETE ==="
